```yaml
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: DarkOrthodox
          output_path: dist/snake.svg
      - name: Push to Repository
        run: |
          git config --global user.name "Snake Bot"
          git config --global user.email "snake-bot@example.com"
          git add dist/snake.svg
          git commit -m "Generate Snake Animation"
          git push
